//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.22 at 09:23:21 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://vocloud.ivoa.cz/spark/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cz.ivoa.vocloud.spark.schema;
