//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.23 at 06:43:35 PM CEST 
//


package cz.ivoa.vocloud.spark.schema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vocloud-server-address" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="local-address" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="spark-executable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hadoop-default-fs" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="max-jobs" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="environment" type="{http://vocloud.ivoa.cz/spark/schema}environment"/>
 *         &lt;element name="submit-params" type="{http://vocloud.ivoa.cz/spark/schema}params-list" minOccurs="0"/>
 *         &lt;element name="workers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="worker" type="{http://vocloud.ivoa.cz/spark/schema}worker" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vocloudServerAddress",
    "localAddress",
    "sparkExecutable",
    "hadoopDefaultFs",
    "maxJobs",
    "description",
    "environment",
    "submitParams",
    "workers"
})
@XmlRootElement(name = "uws-settings")
public class UwsSettings {

    @XmlElement(name = "vocloud-server-address")
    @XmlSchemaType(name = "anyURI")
    protected String vocloudServerAddress;
    @XmlElement(name = "local-address", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String localAddress;
    @XmlElement(name = "spark-executable", required = true)
    protected String sparkExecutable;
    @XmlElement(name = "hadoop-default-fs", required = true)
    protected String hadoopDefaultFs;
    @XmlElement(name = "max-jobs", required = true, defaultValue = "4")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxJobs;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected Environment environment;
    @XmlElement(name = "submit-params")
    protected ParamsList submitParams;
    @XmlElement(required = true)
    protected UwsSettings.Workers workers;

    /**
     * Gets the value of the vocloudServerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVocloudServerAddress() {
        return vocloudServerAddress;
    }

    /**
     * Sets the value of the vocloudServerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVocloudServerAddress(String value) {
        this.vocloudServerAddress = value;
    }

    /**
     * Gets the value of the localAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalAddress() {
        return localAddress;
    }

    /**
     * Sets the value of the localAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalAddress(String value) {
        this.localAddress = value;
    }

    /**
     * Gets the value of the sparkExecutable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSparkExecutable() {
        return sparkExecutable;
    }

    /**
     * Sets the value of the sparkExecutable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSparkExecutable(String value) {
        this.sparkExecutable = value;
    }

    /**
     * Gets the value of the hadoopDefaultFs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHadoopDefaultFs() {
        return hadoopDefaultFs;
    }

    /**
     * Sets the value of the hadoopDefaultFs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHadoopDefaultFs(String value) {
        this.hadoopDefaultFs = value;
    }

    /**
     * Gets the value of the maxJobs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxJobs() {
        return maxJobs;
    }

    /**
     * Sets the value of the maxJobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxJobs(BigInteger value) {
        this.maxJobs = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link Environment }
     *     
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Environment }
     *     
     */
    public void setEnvironment(Environment value) {
        this.environment = value;
    }

    /**
     * Gets the value of the submitParams property.
     * 
     * @return
     *     possible object is
     *     {@link ParamsList }
     *     
     */
    public ParamsList getSubmitParams() {
        return submitParams;
    }

    /**
     * Sets the value of the submitParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamsList }
     *     
     */
    public void setSubmitParams(ParamsList value) {
        this.submitParams = value;
    }

    /**
     * Gets the value of the workers property.
     * 
     * @return
     *     possible object is
     *     {@link UwsSettings.Workers }
     *     
     */
    public UwsSettings.Workers getWorkers() {
        return workers;
    }

    /**
     * Sets the value of the workers property.
     * 
     * @param value
     *     allowed object is
     *     {@link UwsSettings.Workers }
     *     
     */
    public void setWorkers(UwsSettings.Workers value) {
        this.workers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="worker" type="{http://vocloud.ivoa.cz/spark/schema}worker" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "worker"
    })
    public static class Workers {

        protected List<Worker> worker;

        /**
         * Gets the value of the worker property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the worker property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getWorker().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Worker }
         * 
         * 
         */
        public List<Worker> getWorker() {
            if (worker == null) {
                worker = new ArrayList<Worker>();
            }
            return this.worker;
        }

    }

}
